## EJECUTA ESTA CELDA PARA AUTENTICARTE CON TU CUENTA DE GMAIL

In [ ]:
from mooclib import *
import inspect, urllib
html, auth_code, userinfo = google_authenticate(PORT_NUMBER=8080)
html

## EJECUTA LA SIGUIENTE CELDA ANTES DE EMPEZAR TUS EJERCICIOS

In [ ]:
from sklearn.datasets import *
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
%matplotlib inline

def plot_2Ddata_with_boundary(classifier,X,y):
    n = 200
    mins,maxs = np.min(d,axis=0), np.max(d,axis=0)
    mins -= np.abs(mins)*.2
    maxs += np.abs(maxs)*.2
    d0 = np.linspace(mins[0], maxs[0],n)
    d1 = np.linspace(mins[1], maxs[1],n)
    gd0,gd1 = np.meshgrid(d0,d1)
    D = np.hstack((gd0.reshape(-1,1), gd1.reshape(-1,1)))
    p = (classifier.predict(D)*1.).reshape((n,n))
    plt.contourf(gd0,gd1,p, levels=[-0.1,0.5], alpha=0.5, cmap=plt.cm.Greys)
    plt.scatter(X[y==0][:,0], X[y==0][:,1], c="blue")
    plt.scatter(X[y==1][:,0], X[y==1][:,1], c="red")


# Ejercicio 1: API `sklearn`

Organiza el código de las notas en una clase siguiendo el API de `sklearn`. Para esto:

- La función `fit` calcula el $\theta$ óptimo. Observa que a la función le llegan los datos originales en una matrix $\mathbf{R}^{m \times n}$, tendrás que añadirles una columna de 1's.
- El $\theta$ óptimo se guarda en la variable de instancia `self.theta`
- La función `predict` tendrá que añadirle una columna de 1's a los datos que reciba y usar `self.theta` para devolver un vector de predicciones para cada $x^{(i)}$ (cada fila de $X$) de forma que la predicción sea $predict(x^{(i)})=1\{g(\theta\cdot x^{(i)})>0.5\}$. Es decir, ha de devolver un vector de 0's y 1's.

In [ ]:
def LR(**args): # hack for inspect to work with classes
    from scipy.optimize import minimize
    import numpy as np
    
    class LR_class:
        def fit(self, X, y):
            X = ... ## TU CODIGO AQUI. ANADELE UNA COLUMNA DE 1's a X
            def cost(t):
                return  ... ## TU CODIGO AQUI

            def grad(t):
                return ... ## TU CODIGO AQUI
            
            r = minimize(... ## TU CODIGO AQUI)
            self.theta = r.x 

        def predict(self, X):
            X = ... ## TU CODIGO AQUI. ANADELE UNA COLUMNA DE 1's a X
            return ... ## TU CODIGO AQUI. DEVUELVE UN VECTOR DE PREDICCIONES

        def g(self, X):
            return 1/(1+np.exp(-X))
    return LR_class(**args)
                         
import urllib, inspect
src1 = urllib.quote_plus(inspect.getsource(LR))

comprueba tu código

In [ ]:
data = np.loadtxt("data/logregdata.csv", delimiter=",", skiprows=1)[10:20]
d,c = data[:,:2], data[:,2].astype(int)
print d
lr = LR()
lr.fit(d,c)
print "predictions   ", lr.predict(d)
print "actual classes", c
plot_2Ddata_with_boundary(lr, d, c)

In [ ]:
data = np.loadtxt("data/logregdata.csv", delimiter=",", skiprows=1)
d,c = data[:,:2], data[:,2]
lr = LR()
lr.fit(d,c)
plot_2Ddata_with_boundary(lr, d, c)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_1 $src1

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_1 $src1

# Ejercicio 2: Métrica de desempeño

completa el método `score` para que:

- llame al método `predict``
- calcule el porcentaje de aciertos de predicción con respecto a `y`

In [ ]:
def LR(**args): # hack for inspect to work with classes
    from scipy.optimize import minimize
    import numpy as np
    
    class LR_class:
        def fit(self, X, y):
            X = ... ## TU CODIGO AQUI
            def cost(t):
                return ... ## TU CODIGO AQUI

            def grad(t):
                return ... ## TU CODIGO AQUI

            r = minimize(... ## TU CODIGO AQUI)
            self.theta = r.x        

        def predict(self, X):
            X = ... ## TU CODIGO AQUI
            return ... ## TU CODIGO AQUI

        def g(self, X):
            return 1/(1+np.exp(-X))

        def score(self, X,y):
            return ... ## TU CODIGO AQUI
        
    return LR_class(**args)

import urllib, inspect
src2 = urllib.quote_plus(inspect.getsource(LR))

In [ ]:
data = np.loadtxt("data/logregdata.csv", delimiter=",", skiprows=1)
d,c = data[:,:2], data[:,2]
lr = LR()
lr.fit(d,c)
print lr.score(d,c)
plot_2Ddata_with_boundary(lr, d, c)

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_2 $src2

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_2 $src2

# Ejercicio 3: Características polinomiales

completa la función `map_features` para que dada una matrix $X\in \mathbb{R}^{m \times n}$ devuelva otra matrix $\mathbb{R}^{m \times 3n}$ que incluya las columnas originales elevadas al cuadrado y al cubo.

Por ejemplo para la siguiente matriz de entrada:

    [[6 0 2]
     [5 8 9]
     [1 4 9]
     [3 5 1]
     [3 5 3]]
     
debería de devolver la siguiente matriz:

    [[  6   0   2  36   0   4 216   0   8]
     [  5   8   9  25  64  81 125 512 729]
     [  1   4   9   1  16  81   1  64 729]
     [  3   5   1   9  25   1  27 125   1]
     [  3   5   3   9  25   9  27 125  27]]
     

In [ ]:
def LR(**args): # hack for inspect to work with classes
    from scipy.optimize import minimize
    import numpy as np
    class LR_class:

        def map_features(self, X):
            return ... ## TU CODIGO AQUI

        def fit(self, X, y):

            X = ... ## TU CODIGO AQUI. LLAMA A map_features
            X = ... ## TU CODIGO AQUI. ANADE UNA COLUMNA DE 1's
            def cost(t):
                return ... ## TU CODIGO AQUI

            def grad(t):
                return ... ## TU CODIGO AQUI

            r = minimize(... ## TU CODIGO AQUI)
            self.theta = r.x     

        def predict(self, X):
            X = ... ## TU CODIGO AQUI. LLAMA A map_features
            X = ... ## TU CODIGO AQUI. ANADE UNA COLUMNA DE 1's
            return ... ## TU CODIGO AQUI. DEVUELVE EL VECTOR DE PREDICCIONES

        def g(self, X):
            return 1/(1+np.exp(-X))

        def score(self, X,y):
            return ... ## TU CODIGO AQUI. CALCULA EL SCORE
    
    return LR_class(**args)

import urllib, inspect
src3 = urllib.quote_plus(inspect.getsource(LR))

In [ ]:
data = np.loadtxt("data/logregdata.csv", delimiter=",", skiprows=1)[:20]
d,c = data[:,:2], data[:,2]
lr = LR()
lr.fit(d,c)
print lr.score(d,c)
plot_2Ddata_with_boundary(lr, d, c)
print lr.theta

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_3 $src3

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_3 $src3

# Ejercicio 4: Término de regularización

Modificamos la función de coste para penalizar valores grandes de $\theta$ de la siguiente manera:

$$ J(\theta) =  \frac{1}{m}\sum_{i=0}^{m-1} (y^{(i)}-g(\theta\mathbf{x}^{(i)}))^2 + \alpha |\theta|^2$$

donde $\alpha$ es un escalar para controlar la importancia del nuevo término (con $\alpha=0$ tenemos el caso sin regularización) y $|\theta|$ es la norma de $\theta$. Por tanto el gradiente queda actualizado de la siguiente manera:

$$\nabla J= \frac{1}{m}2X^{T}\cdot(g(X\cdot\theta)-Y)+2\alpha|\theta|$$

Modifica las funciones de coste y gradiente para que implementen estas definiciones.

In [ ]:
def LR(**args): # hack for inspect to work with classes

    class LR_class:

        def map_features(self, X):
            return ... ## TU CODIGO AQUI. 

        def fit(self, X, y):
            alpha = 0.00001
            X = ... ## TU CODIGO AQUI. LLAMA A map_features
            X = ... ## TU CODIGO AQUI. ANADE UNA COLUMNA DE 1's
            def cost(t):
                return ... ## TU CODIGO AQUI. NUEVA DEFINICION DEL COSTE

            def grad(t):
                return ... ## TU CODIGO AQUI. NUEVA DEFINICION DEL GRADIENTE

            r = minimize(... ## TU CODIGO AQUI)
            self.theta = r.x     

        def predict(self, X):
            X = ... ## TU CODIGO AQUI. LLAMA A map_features
            X = ... ## TU CODIGO AQUI. ANADE UNA COLUMNA DE 1's
            return ... ## TU CODIGO AQUI. GENERA EL VECTOR DE PREDICCIONES

        def g(self, X):
            return 1/(1+np.exp(-X))

        def score(self, X,y):
            return ... ## TU CODIGO AQUI. DEFINE LA FUNCION DE SCORE   
    
    return LR_class(**args)

import urllib, inspect
src4 = urllib.quote_plus(inspect.getsource(LR))

comprueba tu código ... el valor de los $\theta$ obtenidos ha de ser más pequeño que en los ejercicios anteriores

In [ ]:
data = np.loadtxt("data/logregdata.csv", delimiter=",", skiprows=1)
d,c = data[:,:2], data[:,2]

lr = LR()
lr.fit(d,c)
print lr.score(d,c)
plot_2Ddata_with_boundary(lr, d, c)
print lr.theta

#### evaluate your answer before submitting:

In [ ]:
!./run CHECK_SOLUTION PS3_4 $src4

#### submit your answer (you must be connected to internet)

In [ ]:
!./run SUBMIT_SOLUTION PS3_4 $src4